version: "3.3"
services: 
  app:
    build: web
    image: cars-app
    ports:
      - 3000:3000
  db: 
    build: db
    image: sample-db
    volumes: 
      - sample-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
volumes:
  sample-data:
